### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by gunhippy** [execsuroot/better-shulkers#1]
It is possible to duplicate the contents of a shulker.

Steps to repeat:

1) place shulker on hotbar with content included.

2) right click shulker and take all contents out into player inventory

3) whilst the shulker is still open, move the shulker from the hotbar into the player inventory

4) close shulker

5) move shulker from inventory back onto hotbar and open

Following this process you'll find that the contents of the shulker box is still in the shulkerbox, but it is also in your inventory

**Comment by gunhippy** [comment]
Video of the above process
https://github.com/user-attachments/assets/0c4c241d-70ab-4f91-a482-b2b4128af2ec

**Comment by execsuroot** [comment]
Fixed in #cae29bf (1.0.1)

**Comment by gunhippy** [comment]
Confirmed, fix works perfectly! Thank you for sorting so quickly
